-- MySQL Script generated by MySQL Workbench
-- Thu Mar  3 14:22:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema postres
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema postres
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `postres` DEFAULT CHARACTER SET utf8 ;
USE `postres` ;

-- -----------------------------------------------------
-- Table `postres`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postres`.`usuario` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numeroIdentificacion` BIGINT(11) NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `apellido` VARCHAR(200) NOT NULL,
  `telefono` BIGINT(15) NOT NULL,
  `correo` VARCHAR(200) NULL,
  `rol` ENUM('Administrador', 'Empleado') NOT NULL,
  `contrasena` VARCHAR(200) NULL,
  `estado` ENUM("Activo", "Inactivo") NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `postres`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postres`.`departamentos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) NOT NULL,
  `region` ENUM('Caribe', 'Centro Oriente', 'Centro Sur', 'Eje Cafetero - Antioquia', 'Llano', 'Pacífico') NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `departamentos_nombre_unique` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `postres`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postres`.`municipios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `departamento_id` INT UNSIGNED NOT NULL,
  `acortado` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `estado` ENUM('Activo', 'Inactivo') CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT 'Activo',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `municipios_nombre_index` (`nombre` ASC) VISIBLE,
  INDEX `municipios_departamento_id_index` (`departamento_id` ASC) VISIBLE,
  CONSTRAINT `municipios_departamento_id_foreign`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `postres`.`departamentos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 99774
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `postres`.`domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postres`.`domicilio` (
  `idDomicilio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(200) NOT NULL,
  `telefono` VARCHAR(200) NOT NULL,
  `municipios_id` INT UNSIGNED NOT NULL,
  `Usuario_idUsuario` INT UNSIGNED NOT NULL,
  `municipios_id1` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idDomicilio`),
  INDEX `fk_Domicilio_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_domicilio_municipios1_idx` (`municipios_id1` ASC) VISIBLE,
  CONSTRAINT `fk_Domicilio_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `postres`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domicilio_municipios1`
    FOREIGN KEY (`municipios_id1`)
    REFERENCES `postres`.`municipios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `postres`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postres`.`venta` (
  `idVenta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numeroVenta` INT(10) NOT NULL,
  `fecha` DATE NOT NULL,
  `total` VARCHAR(200) NOT NULL,
  `costoDomicilio` VARCHAR(200) NULL,
  `estado` ENUM('Aprobada', 'No aprobada') NOT NULL,
  `Usuario_idUsuario` INT UNSIGNED NOT NULL,
  `domicilio_idDomicilio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Venta_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_venta_domicilio1_idx` (`domicilio_idDomicilio` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `postres`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_domicilio1`
    FOREIGN KEY (`domicilio_idDomicilio`)
    REFERENCES `postres`.`domicilio` (`idDomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `postres`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postres`.`producto` (
  `idProducto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `valorUnitario` VARCHAR(200) NOT NULL,
  `estado` ENUM('Disponible', 'No Disponible') NOT NULL,
  `stock` INT(10) NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `postres`.`detalleVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postres`.`detalleVenta` (
  `idDetalleVenta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` INT(10) NOT NULL,
  `fechaVencimiento` DATE NOT NULL,
  `numDetalleVenta` INT(10) NOT NULL,
  `Venta_idVenta` INT UNSIGNED NOT NULL,
  `Producto_idProducto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idDetalleVenta`),
  INDEX `fk_DetalleVenta_Venta1_idx` (`Venta_idVenta` ASC) VISIBLE,
  INDEX `fk_DetalleVenta_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_DetalleVenta_Venta1`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `postres`.`venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleVenta_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `postres`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `postres`.`usuario_has_domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postres`.`usuario_has_domicilio` (
  `Usuario_idUsuario` INT(10) UNSIGNED NOT NULL,
  `Domicilio_id_Domicilio` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Domicilio_id_Domicilio`),
  INDEX `fk_Usuario_has_Domicilio_Domicilio1_idx` (`Domicilio_id_Domicilio` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Domicilio_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Domicilio_Domicilio1`
    FOREIGN KEY (`Domicilio_id_Domicilio`)
    REFERENCES `postres`.`domicilio` (`idDomicilio`),
  CONSTRAINT `fk_Usuario_has_Domicilio_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `postres`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `postres`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postres`.`pago` (
  `idPago` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `abono` VARCHAR(200) NOT NULL,
  `saldo` VARCHAR(200) NOT NULL,
  `fechaPago` DATE NOT NULL,
  `descuento` VARCHAR(200) NULL,
  `estado` ENUM('Cancelado', 'Pendiente') NULL,
  `Venta_idVenta` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `fk_Pago_Venta1_idx` (`Venta_idVenta` ASC) VISIBLE,
  CONSTRAINT `fk_Pago_Venta1`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `postres`.`venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `postres`.`Usuario_has_Domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `postres`.`Usuario_has_Domicilio` (
  `Usuario_idUsuario` INT UNSIGNED NOT NULL,
  `Domicilio_id_Domicilio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Domicilio_id_Domicilio`),
  INDEX `fk_Usuario_has_Domicilio_Domicilio1_idx` (`Domicilio_id_Domicilio` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Domicilio_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Domicilio_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `postres`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Domicilio_Domicilio1`
    FOREIGN KEY (`Domicilio_id_Domicilio`)
    REFERENCES `postres`.`domicilio` (`idDomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
