-- MySQL Script generated by MySQL Workbench
-- Wed Feb  9 15:33:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Postres
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Postres
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Postres` DEFAULT CHARACTER SET utf8 ;
USE `Postres` ;

-- -----------------------------------------------------
-- Table `Postres`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Postres`.`Usuario` (
  `idEmpleado` BIGINT(11) NOT NULL,
  `numeroIdentificacion` BIGINT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(11) NOT NULL,
  `correo` VARCHAR(45) NULL,
  `rol` ENUM('Administrador', ' Empleo', 'Cliente') NOT NULL,
  `contrasena` BIGINT(8) NULL,
  `estado` ENUM("Activo", "Inactivo") NOT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Postres`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Postres`.`departamentos` (
  `id` BIGINT(19) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) NOT NULL,
  `region` ENUM('Caribe', 'Centro Oriente', 'Centro Sur', 'Eje Cafetero - Antioquia', 'Llano', 'Pacífico') NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `departamentos_nombre_unique` (`nombre` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Postres`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Postres`.`municipios` (
  `id` BIGINT(19) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `departamento_id` BIGINT(19) UNSIGNED NOT NULL,
  `acortado` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `estado` ENUM('Activo', 'Inactivo') CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT 'Activo',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `municipios_nombre_index` (`nombre` ASC),
  INDEX `municipios_departamento_id_index` (`departamento_id` ASC),
  CONSTRAINT `municipios_departamento_id_foreign`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `Postres`.`departamentos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 99774
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Postres`.`Domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Postres`.`Domicilio` (
  `id_Domicilio` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `Municipio_idMunicipio` INT NOT NULL,
  `Usuario_idEmpleado` BIGINT(11) NOT NULL,
  `municipios_id` BIGINT(19) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Domicilio`),
  INDEX `fk_Domicilio_Usuario1_idx` (`Usuario_idEmpleado` ASC),
  INDEX `fk_Domicilio_municipios1_idx` (`municipios_id` ASC),
  CONSTRAINT `fk_Domicilio_Usuario1`
    FOREIGN KEY (`Usuario_idEmpleado`)
    REFERENCES `Postres`.`Usuario` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Domicilio_municipios1`
    FOREIGN KEY (`municipios_id`)
    REFERENCES `Postres`.`municipios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Postres`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Postres`.`Venta` (
  `idVenta` BIGINT(10) NOT NULL,
  `numeroVenta` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `total` VARCHAR(45) NOT NULL,
  `costo_domicilio` VARCHAR(45) NULL,
  `Domicilio_id_Domicilio` INT NULL,
  `estado` ENUM('Realizada', 'NO_Realizada', 'Pendiente') NOT NULL,
  `Usuario_idEmpleado` BIGINT(11) NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Venta_Domicilio1_idx` (`Domicilio_id_Domicilio` ASC),
  INDEX `fk_Venta_Usuario1_idx` (`Usuario_idEmpleado` ASC),
  CONSTRAINT `fk_Venta_Domicilio1`
    FOREIGN KEY (`Domicilio_id_Domicilio`)
    REFERENCES `Postres`.`Domicilio` (`id_Domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Usuario1`
    FOREIGN KEY (`Usuario_idEmpleado`)
    REFERENCES `Postres`.`Usuario` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Postres`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Postres`.`Producto` (
  `idProducto` BIGINT(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `valorUnitario` INT NOT NULL,
  `estado` ENUM('Disponible', 'noDisponible') NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Postres`.`DetalleVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Postres`.`DetalleVenta` (
  `idDetalleVenta` BIGINT(10) NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `fechaVencimiento` DATE NOT NULL,
  `Venta_idVenta` BIGINT(10) NOT NULL,
  `Producto_idProducto` BIGINT(10) NOT NULL,
  PRIMARY KEY (`idDetalleVenta`),
  INDEX `fk_DetalleVenta_Venta1_idx` (`Venta_idVenta` ASC),
  INDEX `fk_DetalleVenta_Producto1_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_DetalleVenta_Venta1`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `Postres`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleVenta_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Postres`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Postres`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Postres`.`Pago` (
  `idPago` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `abono` INT NOT NULL,
  `saldo` VARCHAR(45) NOT NULL,
  `fechaPago` DATE NOT NULL,
  `descuento` VARCHAR(45) NULL,
  `estado` ENUM('Cancelado', 'Debe') NULL,
  `Venta_idVenta` BIGINT(10) NOT NULL,
  `Usuario_idEmpleado` BIGINT(11) NOT NULL,
  PRIMARY KEY (`idPago`, `Usuario_idEmpleado`),
  INDEX `fk_Pago_Venta1_idx` (`Venta_idVenta` ASC),
  INDEX `fk_Pago_Usuario1_idx` (`Usuario_idEmpleado` ASC),
  CONSTRAINT `fk_Pago_Venta1`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `Postres`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pago_Usuario1`
    FOREIGN KEY (`Usuario_idEmpleado`)
    REFERENCES `Postres`.`Usuario` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Postres`.`suario_has_Domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Postres`.`suario_has_Domicilio` (
  `Usuario_idUsuario` BIGINT(11) NOT NULL,
  `Domicilio_id_Domicilio` INT NOT NULL,
  PRIMARY KEY (`Usuario_idEmpleado`, `Domicilio_id_Domicilio`),
  INDEX `fk_Usuario_has_Domicilio_Domicilio1_idx` (`Domicilio_id_Domicilio` ASC),
  INDEX `fk_Usuario_has_Domicilio_Usuario1_idx` (`Usuario_idEmpleado` ASC),
  CONSTRAINT `fk_Usuario_has_Domicilio_Usuario1`
    FOREIGN KEY (`Usuario_idEmpleado`)
    REFERENCES `Postres`.`Usuario` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Domicilio_Domicilio1`
    FOREIGN KEY (`Domicilio_id_Domicilio`)
    REFERENCES `Postres`.`Domicilio` (`id_Domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
